import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MainMenu } from "@/components/MainMenu/MainMenu";
import { Footer } from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ovnisa Dev Site",
  description: "Generated by TUCO",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
